jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-name
          path: ./path-to-artifacts

      # باقي الخطوات الخاصة بـ workflow
